# Generated by Django 2.2.3 on 2019-08-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('cote', models.FloatField()),
                ('image', models.ImageField(default='eqp.jpg', upload_to='equipe_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Exterieure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('cote', models.FloatField()),
                ('image', models.ImageField(default='eqp.jpg', upload_to='equipe_pics')),
            ],
        ),
    ]
